apiVersion: v1
data:
  EVENT_TOPIC: '{{ .Values.config_maps.event_topic }}'
kind: ConfigMap
metadata:
  namespace: '{{ .Values.namespace }}'
  labels:
    app: publisher
  name: '{{ .Values.project_id }}-publisher-config-maps-{{ .Values.region }}'
