apiVersion: v1
data:
  EVENT_SUBSCRIPTION: '{{ .Values.config_maps.event_subscription }}'
  METRIC_TOPIC: '{{ .Values.config_maps.metric_topic }}'
  METRIC_APP_PORT: '{{ .Values.config_maps.metric_app_port }}'
kind: ConfigMap
metadata:
  namespace: '{{ .Values.namespace }}'
  labels:
    app: subscriber
  name: '{{ .Values.project_id }}-subscriber-config-maps-{{ .Values.region }}'
